### ISSUE TITLE
Interested in adding TLD for countries as well?

### ISSUE THREAD

**Issue by jwcobb** [ffsantos92/laracountries#1]
I have a similar table that I use a lot and I have another column for the TLD assigned to that country. Are you interested in a PR to add that?

**Comment by fabiofdsantos** [comment]
Hi @jwcobb,

Creation and delegation of ccTLDs is described in [RFC 1591](http://tools.ietf.org/html/rfc1591), corresponding to ISO 3166-1 alpha-2 country codes.

There are a very few exceptions. For example, in the United Kingdom both .uk and .gb are reserved as ccTLDs. However, .gb fallen into disuse in favour of .uk.
