### ISSUE TITLE
Class 'CountryTableSeeder' instead of 'CountriesTableSeeder'

### ISSUE THREAD

**Issue by mwumvaxgh** [ffsantos92/laracountries#4]
Hi there.
Not sure if this is a critical issue, but I suggest you update the class name in seeds/CountriesTableSeeder.php **from CountryTableSeeder** to match the file name **CountriesTableSeeder**.

**Comment by fabiofdsantos** [comment]
Hi @fordarnold,

Oops, my mistake. I've just committed your suggestion @ https://github.com/ffsantos92/laracountries/commit/1686a57d9ed3a8455423f8e0183237e1b6741b06

Thanks!
