### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Tjoosten** [ffsantos92/laracountries#5]
Maybe you can ad this project to the repo his readme? 

https://github.com/Tjoosten/LaraCity-Belguim

**Comment by fabiofdsantos** [comment]
@Tjoosten, i don't see any reason to add a reference to [LaraCity-Belguim](https://github.com/Tjoosten/LaraCity-Belguim) since this repository is related with countries.

Anyway, thanks for your comment!
